### ISSUE TITLE
api key error

### ISSUE THREAD

**Issue by Alphatiger** [JimmyMakesThings/cordova-plugin-digits#3]
Dear

Is this working, as we tried it is saying the api key is invalid we confirmed from fabric support team that our api key was given all necessary permissions.

ionic run android is throwing crashlytics api key error.

previously we are using digits web plugin from yangli, was thinking of migrating to this.

Any help appreciated.

Issue with permissions, got it resolved with fabric service team

**Comment by derwaldgeist** [comment]
Maybe it's the same problem as #6

**Comment by Alphatiger** [comment]
Resolved
